blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/tox-dev/PyVenvManage?tab=readme-ov-file#pyvenvmanage
    about: Check the README file in the first place.
